# JVM / Network Properties
org.gradle.jvmargs=-Xmx2G -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true
systemProp.java.net.preferIPv4Stack=true
systemProp.java.net.preferIPv4Addresses=true
org.gradle.parallel=true

# Fabric Loom Properties
fabric.loom.disableObfuscation=true

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.5

# Mod Properties
mod_version=1.0.0
maven_group=com.vanillahack
archives_base_name=vanillahack
